### ISSUE TITLE
Issue with checkLinks Method

### ISSUE THREAD

**Issue by johannesschobel** [tembra/jsonapi-errors-php#1]
Hey @tembra ,

I just took a first look at your plugin - awesome work! It looks really nice and I will sure try to use this package! :+1: thanks so far for your work!

I just stumbled accross one issue:
The method `checkLink(...)` in your main class file should be named `checkLinks(...)` (notice the `s` for pluralization!). Otherwise it raises a `method not found` Exception (e.g., in Line 230 you call the `checkLinks(...)` method, which is not available!

Cheers and Greetings
Johannes

**Comment by tembra** [comment]
Hello @johannesschobel 

Thanks for your observation. I change the `link` to `links` probably os last commit and for sure I didnt test it at all. I'll also add some tests to this package on the milestone to 1.0, so this wont be happen again.

Thank you for your feedback :)

**Comment by tembra** [comment]
This issue was solved with new commit [f38ad22](https://github.com/tembra/jsonapi-errors-php/commit/f38ad22dc69e1dffbd8e1930a829b6590551ff39).
