### ISSUE TITLE
Best Practices for Errors

### ISSUE THREAD

**Issue by johannesschobel** [tembra/jsonapi-errors-php#2]
Dear @tembra ,

thanks a lot for your plugin - its awesome and really easy to use!
However, I have a few questions regarding "Best Practices" for errors within the application.

As you mentioned in your [wiki](https://github.com/tembra/jsonapi-errors-php/wiki/Application-Error-Codes) it is recommended to create an own class to extend the provided error class.

Consider the following example:
I would like to create multiple error classes (e.g., one class for all errors regarding the `user` object, one class for all errors regarding the `group` object, one class for all errors ... ). This would result in multiple files:

``` php
class UserException extends MyJsonApiErrors { /* ... */ } 
class GroupException extends MyJsonApiErrors { /* ... */ }
/* and so on */
```

Then I could raise an `UserNotFound` Exception by calling 

``` php
UserException::error([UserException::USER_NOT_FOUND]); // the ENUM USER_NOT_FOUND must be defined in respectie UserException class
```

Would you split your errors into multiple files / classes (as I have shown above), or would you rather use one "generic" `OBJECT_NOT_FOUND` error and further specify this error with an additional `detail` attribute (e.g., "`user` not found")?

In my opinion, the approach above (multiple classes) is way better readable, extendable and maintainable. What do you think? Maybe we can extend the docs / wiki at this point to guide future users?

Greetings from Germany,
Johannes

**Comment by tembra** [comment]
Hello @johannesschobel 

That's cool you are using on your projects. I'm happy to help.

> Would you split your errors into multiple files / classes (as I have shown above), or would you rather use one "generic" OBJECT_NOT_FOUND error and further specify this error with an additional detail attribute (e.g., "user not found")?

Well I guess this is too particular. But I would use a generic not found error except if it is too important to distingue both. My second answer shows why.

> In my opinion, the approach above (multiple classes) is way better readable, extendable and maintainable. What do you think? Maybe we can extend the docs / wiki at this point to guide future users?

You are correct. It is better readable and extendable, but **it is not** better maintainable. I think each application needs to have only one error class that you need to maintain or call on doubt. But if you have very specific errors for each type of resource inside a unique application this really could be better.

Overall the question is: Why you need going too deep into error codes? Is the error too difficult to manage? Can't you give a stack trace on `meta` for this cases? Or maybe a `links` object with more information? Or even an `id` for this particular occurrence of the problem?

Remember that every application error needs to have a documentation (that this package will cover until version 1.0). So if you have multiple class you'll need to generate multiple documentations and by someway merge them all.

Finally I guess that everyone can handle this point by themselves and choose if they want to have one or multiple class for error codes. Like you thought this way, others can think too. Probably if more persons has the same doubt/idea I can reference this issue on [Recommendations](https://github.com/tembra/jsonapi-errors-php/wiki/Recommendations) topic.

**Comment by johannesschobel** [comment]
Dear @tembra ,

but think about the different Exception classes as kind of `packages` like, for example, in Java. Each constant you define (e.g., `const USER_NOT_FOUND = 1`) in your class (e.g., in the `UserException` class) corresponds to one specific Exception. One class, however, is similar to one package, "grouping" respective exceptions...

I think, this question may depend on how the documentation of the errors will be handled. If it is possible to create a "javadoc"-like documentation, where each error (i.e., each `const` within the classes) has its separate file, this still would be a practicable solution (in my opinion).

Furthermore, one need to discuss, how respective methods shall be annotated to correctly _link_ to respective errors.

I hope you understand, what / how I mean?
Greetings from Germany,
Johannes

**Comment by tembra** [comment]
Yeah. I got you. But this is not about class or group errors, right? It is about application errors.

As I mentioned on my last answer, you can do this for your convenience or for better control/maintain of very specific errors for each type of resource inside an unique application. I do not discourage this. I even recommend.

For documentation I'm planning to create a separate file for each class that extends `MyJsonApiErrors` as you thought. Basically the package will generate an error table with codes (from constants) which in turn may have respective title, detail and other members declared into `$errors` array.

Probably now it is clearly that it must be added on [Recommendations](https://github.com/tembra/jsonapi-errors-php/wiki/Recommendations) topic :)

**Comment by johannesschobel** [comment]
My initial thought about this topic was, that I would like to keep my controllers "slim" with respect to throwing errors.

For example, I would rather use

``` php
UserException::error([UserException::USER_NOT_FOUND]);
```

than

``` php
ApiException::error([ApiException::NOT_FOUND => [
   'title' => 'User not found',
   'detail' => 'The requested user was not found'
]]);
```

for cleaner code. Therefore, I thought that it would be good to specify the errors on a more fine-granular basis (and hence split into separate files as described earlier).

What is your roadmap and schedule for the `1.0 version` of the plugin?
Is it possible to _integrate_ the error-documentation (of your plugin) into the api-blueprint documentation of  `dingo/api`? 

Greetings,
Johannes

**Comment by tembra** [comment]
You are correct. I manage to maintain my controllers clean/slim. I always use the first code you wrote. Even because the second code the future documentation function of this package will not be able to read.

I wrote this package for an application that I'm building. My plan is to release it on the late second half of this year. When it is released it will be with API documentation so this package needs to have this already done.

About `dingo/api` documentation, yeah it is possible and probably I would do this.

**Comment by johannesschobel** [comment]
Just to clarify:
By

> I always use the first code you wrote

you refer to

``` php
UserException::error([UserException::USER_NOT_FOUND]);
```

right?

I am happy if I may be able to contribute to this plugin (allbe it only through discussion using issues) :tada: I will give additional feedback when I have time to work on my project and dig further into application errors ;)

Cheers

**Comment by tembra** [comment]
Right.

You're welcome to contribute. This discussions is always valuable to enhancement of every package :)
